### ISSUE TITLE
globalActions cannot be set without any places

### ISSUE THREAD

**Issue by Yivan** [YouweGit/pimcore-workflow-gui#44]
Hello,

Global actions cannot be set without any places.
For instance this one (default Pimcore demo) won't work:
```
            globalActions:
                log_time:
                    label: 'Log Time'
                    guard: "is_fully_authenticated()"
                    notes:
                        commentEnabled: true
                        commentRequired: true
                        type: 'Worklog'
                        title: 'Time Logged'
                        additionalFields:
                            - name: 'timeWorked'
                              fieldType: 'input'
                              title: 'Time spent'
                              required: true
```

When saving the workflow on Workflow GUI the following error is returned if no `to:` place is set:
`The path "pimcore.workflows.senzo.globalActions.log.to" should have at least 1 element(s) defined.`

But it should work without any `to:` has this is a global parameter.
As effect of this bug, for now it is not possible to set a global action workflow which do not transition.

Thanks.

**Comment by jorisros** [comment]
@Yivan seems that this issue has been solved.
![Screenshot_20220112_133414](https://user-images.githubusercontent.com/752283/149141439-c97ccbf2-483d-4270-9a52-f669eed5484f.png)
With following workflow
```
pimcore:
    workflows:
        exampleWorkflow:
            enabled: true
            priority: 1
            label: 'Example workflow'
            initial_markings: placeA
            type: workflow
            audit_trail:
                enabled: true
            marking_store:
                type: state_table
            support_strategy:
                type: expression
                arguments:
                    - Pimcore\Model\DataObject\Test
                    - is_fully_authenticated()
            places:
                placeA:
                    visibleInHeader: true
                    title: 'Place A'
                    label: 'Place A'
                    color: '#eb0058'
                placeB:
                    title: 'Place B'
                    visibleInHeader: true
                    label: 'Place B'
                    color: '#00800f'
            transitions:
                placeAtoB:
                    from:
                        - placeA
                    to:
                        - placeB
                    options:
                        label: 'Place A to B'
                        changePublishedState: no_change
                        notes:
                            commentEnabled: false
                            additionalFields: {  }
            globalActions:
                log_time:
                    label: 'Log Time'
                    guard: "is_fully_authenticated()"
                    notes:
                        commentEnabled: true
                        commentRequired: true
                        type: 'Worklog'
                        title: 'Time Logged'
                        additionalFields:
                            -   name: 'timeWorked'
                                fieldType: 'input'
                                title: 'Time spent'
                                required: true
```
